/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earthBallStart1.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earthBallStart1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[0, 0, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.21, 0.78, -0.58]} rotation={[2.35, -0.58, -0.25]} scale={-0.01} />
    </group>
  )
}

useGLTF.preload('/earthBallStart1.gltf')
