/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earthBallStart3.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earthBallStart3.gltf')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={2.19} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.48, 1.69, -1.28]} rotation={[2.35, -0.58, -0.26]} scale={-0.04} >
      <meshLambertMaterial attach='material' color='white'/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/earthBallStart3.gltf')
