/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earthBallStart2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/earthBallStart2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={1.8} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.39, 1.39, -1.05]} rotation={[2.35, -0.58, -0.26]} scale={-0.02} >
        <meshLambertMaterial attach='material' color='black'/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/earthBallStart2.gltf')
