/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earthMarkers.gltf
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function EarthMarkers(props) {
  const { nodes, materials } = useGLTF('/earthMarkers.gltf')
  const rotationRef = useRef(null);
  const [rotationRate, setRotationRate] = useState(0.001);
  const {setCityHover} = props;

  useFrame(() => {
    if (!rotationRef.current) {
      return;
    }
    rotationRef.current.rotation.y += rotationRate;
  })

  const cityHoverHandler = (cityName) => {
    setRotationRate(0);
    setCityHover(cityName);
  }

  const cityHoverOutHandler = () => {
    setRotationRate(0.001);
    setCityHover('');
  }

  return (
    <group {...props} dispose={null} ref={rotationRef} rotation={[.4 , 2.7 , 0]} scale={.7}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={2.19} />
      {/* <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.48, 1.69, -1.28]} rotation={[2.35, -0.58, -0.26]} scale={-0.04} >
        <meshLambertMaterial attach='material' color='white'/>
      </mesh> */}
      <mesh geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[-0.36, 1.44, -1.57]} rotation={[2.2, -0.55, -0.21]} scale={-0.04} onClick={() => console.log('Rome')} onPointerOver={() => cityHoverHandler('Rome')} onPointerOut={cityHoverOutHandler}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[0.01, 1.71, -1.34]} rotation={[2.47, -0.59, 0.01]} scale={-0.04} onClick={() => console.log('London')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-0.48, 1.69, -1.28]} rotation={[2.35, -0.58, -0.26]} scale={-0.04} onClick={() => console.log('Cracow')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[0.24, 1.37, -1.66]} rotation={[2.32, -0.58, 0.13]} scale={-0.04} onClick={() => console.log('Lisbon')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[-0.96, 1.09, -1.6]} rotation={[1.94, -0.43, -0.52]} scale={-0.04} onClick={() => console.log('Cairo')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[-1.61, 0.9, -1.13]} rotation={[1.83, -0.34, -0.92]} scale={-0.04} onClick={() => console.log('Dubai')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[-0.12, 0.25, -2.14]} rotation={[1.66, -0.35, -0.06]} scale={-0.04} onClick={() => console.log('Lagos')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[-0.59, -1.21, -1.69]} rotation={[0.89, -0.21, -0.28]} scale={-0.04} onClick={() => console.log('Capetown')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[-1.3, -0.03, -1.73]} rotation={[1.23, -0.39, -0.72]} scale={-0.04} onClick={() => console.log('Nairobi')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[-1.52, -0.66, -1.39]} rotation={[0.98, -0.16, -0.79]} scale={-0.04} onClick={() => console.log('Antananarivo')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere011.geometry} material={nodes.Sphere011.material} position={[-1.97, 0.66, -0.59]} rotation={[1.78, -0.25, -1.24]} scale={-0.04} onClick={() => console.log('Bombay')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere012.geometry} material={nodes.Sphere012.material} position={[-1.49, 1.53, -0.36]} rotation={[2.06, -0.65, -1.08]} scale={-0.04} onClick={() => console.log('Almaty')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere013.geometry} material={nodes.Sphere013.material} position={[-2.06, 0.52, 0.39]} rotation={[1.79, -0.27, -1.7]} scale={-0.04} onClick={() => console.log('Bangkok')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere014.geometry} material={nodes.Sphere014.material} position={[-1.48, 1.39, 0.74]} rotation={[1.67, -0.77, -1.85]} scale={-0.04} onClick={() => console.log('Beijing')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere015.geometry} material={nodes.Sphere015.material} position={[-1.59, 1.12, 0.95]} rotation={[1.71, -0.67, -1.93]} scale={-0.04} onClick={() => console.log('Shanghai')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere016.geometry} material={nodes.Sphere016.material} position={[-1.37, 1.32, 1.03]} rotation={[1.64, -0.79, -2.02]} scale={-0.04} onClick={() => console.log('Seoul')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere017.geometry} material={nodes.Sphere017.material} position={[-1.14, 1.27, 1.33]} rotation={[1.59, -0.85, -2.23]} scale={-0.04} onClick={() => console.log('Tokyo')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere018.geometry} material={nodes.Sphere018.material} position={[-2.05, -0.25, 0.63]} rotation={[1.85, 0.02, -1.9]} scale={-0.04} onClick={() => console.log('Jakarta')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere019.geometry} material={nodes.Sphere019.material} position={[-1.65, -1.14, 0.81]} rotation={[2.03, 0.38, -2.17]} scale={-0.04} onClick={() => console.log('Perth')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere020.geometry} material={nodes.Sphere020.material} position={[-0.9, -1.24, 1.53]} rotation={[2.05, 0.39, -2.67]} scale={-0.04} onClick={() => console.log('Sydney')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere021.geometry} material={nodes.Sphere021.material} position={[-0.16, -1.31, 1.72]} rotation={[2.19, 0.43, -3.07]} scale={-0.04} onClick={() => console.log('Auckland')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere022.geometry} material={nodes.Sphere022.material} position={[-0.2, 1.88, -1.06]} rotation={[2.55, -0.61, -0.11]} scale={-0.04} onClick={() => console.log('Oslo')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere023.geometry} material={nodes.Sphere023.material} position={[0.34, 1.95, -0.88]} rotation={[2.83, -0.6, 0.2]} scale={-0.04} onClick={() => console.log('Reykjavik')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere024.geometry} material={nodes.Sphere024.material} position={[1.52, 1.51, -0.31]} rotation={[-2.98, -0.35, 0.85]} scale={-0.04} onClick={() => console.log('Melbourne')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere025.geometry} material={nodes.Sphere025.material} position={[1.58, 1.41, -0.45]} rotation={[-3.01, -0.38, 0.92]} scale={-0.04} onClick={() => console.log('New York')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere026.geometry} material={nodes.Sphere026.material} position={[1.91, 0.96, -0.33]} rotation={[-2.93, -0.26, 1.16]} scale={-0.04} onClick={() => console.log('Miami')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere027.geometry} material={nodes.Sphere027.material} position={[1.63, 1.39, 0.35]} rotation={[-2.77, -0.11, 0.86]} scale={-0.04} onClick={() => console.log('Denver')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere028.geometry} material={nodes.Sphere028.material} position={[1.5, 1.27, 0.91]} rotation={[-2.59, 0.08, 0.77]} scale={-0.04} onClick={() => console.log('San Francisco')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere029.geometry} material={nodes.Sphere029.material} position={[0.52, 1.9, 0.92]} rotation={[-2.7, 0.02, 0.25]} scale={-0.04} onClick={() => console.log('Anchorage')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere030.geometry} material={nodes.Sphere030.material} position={[1.99, 0.76, 0.34]} rotation={[-2.81, 0.03, 1.19]} scale={-0.04} onClick={() => console.log('Mexico City')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere031.geometry} material={nodes.Sphere031.material} position={[2.02, 0.76, -0.03]} rotation={[-2.86, -0.11, 1.23]} scale={-0.04} onClick={() => console.log('Merida')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere032.geometry} material={nodes.Sphere032.material} position={[1.92, 0.69, -0.7]} rotation={[-2.98, -0.4, 1.3]} scale={-0.04} onClick={() => console.log('Santo Domingo')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere033.geometry} material={nodes.Sphere033.material} position={[2.09, 0.34, -0.42]} rotation={[-2.95, -0.23, 1.45]} scale={-0.04} onClick={() => console.log('Panama')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere034.geometry} material={nodes.Sphere034.material} position={[2.05, -0.45, -0.49]} rotation={[-2.95, -0.19, 1.82]} scale={-0.04} onClick={() => console.log('Lima')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere035.geometry} material={nodes.Sphere035.material} position={[1.38, -0.83, -1.44]} rotation={[-2.73, -0.62, 2.22]} scale={-0.04} onClick={() => console.log('Rio De Janeiro')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere036.geometry} material={nodes.Sphere036.material} position={[1.25, -0.23, -1.75]} rotation={[-2.56, -0.81, 2.14]} scale={-0.04} onClick={() => console.log('Natal')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere037.geometry} material={nodes.Sphere037.material} position={[1.26, -1.7, -0.47]} rotation={[-3.09, -0.29, 2.48]} scale={-0.04} onClick={() => console.log('Rio Gallegos')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
      <mesh geometry={nodes.Sphere038.geometry} material={nodes.Sphere038.material} position={[1.51, -1.24, -0.93]} rotation={[-2.94, -0.42, 2.26]} scale={-0.04} onClick={() => console.log('Buenos Aires')}>
        <meshLambertMaterial attach='material' color='white'/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/earthMarkers.gltf')
