/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 earthCones.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three';
import { useFrame } from '@react-three/fiber';

export function Model(props) {
  const { nodes, materials } = useGLTF('/earthCones.gltf')
  const rotationRef = useRef(null);

  useFrame(() => {
    if (!rotationRef.current) {
      return;
    }
    rotationRef.current.rotation.y += 0.001;
  })

  return (
    <group ref={rotationRef} {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} rotation={[0, 0, 0]} position={[0, 0, 0]} scale={[2, 2, 2]}/>
      <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[0.05, 2, -0.75]} rotation={[-0.87, -0.03, -0.05]} scale={[0.02, 0.02, 0.03]} onClick={() => console.log('Hiszpania')}/>
      <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[0.1, 0.64, -0.75]} rotation={[-0.87, -0.03, -0.05]} scale={[0.02, 0.02, 0.03]} onClick={() => console.log('Hiszpania')}>
        <meshLambertMaterial attach='material' color='red'/>
      </mesh>
      <mesh geometry={nodes.Cone001.geometry} material={nodes.Cone001.material} position={[-0.2, 0.78, -0.58]} rotation={[-0.65, -0.01, 0.21]} scale={[0.02, 0.02, 0.03]} onClick={() => console.log('Polska')}/>
    </group>
  )
}

useGLTF.preload('/earthCones.gltf')
