import './globals.css';
import Navbar from './Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Navbar />
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
